local Properties = {
    ["ShirtGraphic"] = {
        "Color3",
        "Graphic",
    },
    ["LocalizationTable"] = {
        "SourceLocaleId",
    },
    ["ImporterGroupSettings"] = {
        "InsertInWorkspace",
        "Anchored",
        "ImportAsModelAsset",
    },
    ["BallSocketConstraint"] = {
        "LimitsEnabled",
        "Radius",
        "TwistLowerAngle",
        "MaxFrictionTorque",
        "Restitution",
        "TwistLimitsEnabled",
        "UpperAngle",
        "TwistUpperAngle",
    },
    ["BrickColorValue"] = {
        "Value",
    },
    ["Accoutrement"] = {
        "AttachmentRight",
        "AttachmentPos",
        "AttachmentPoint",
        "AttachmentUp",
        "AttachmentForward",
    },
    ["DebuggerManager"] = {
        "DebuggingEnabled",
    },
    ["VectorForce"] = {
        "Force",
        "RelativeTo",
        "ApplyAtCenterOfMass",
    },
    ["SelectionLasso"] = {
        "Humanoid",
    },
    ["Handles"] = {
        "Faces",
        "Style",
    },
    ["Stats"] = {
        "PrimitivesCount",
        "ContactsCount",
        "InstanceCount",
        "DataReceiveKbps",
        "PhysicsReceiveKbps",
        "DataSendKbps",
        "HeartbeatTimeMs",
        "PhysicsStepTimeMs",
        "PhysicsSendKbps",
        "MovingPrimitivesCount",
    },
    ["Smoke"] = {
        "Enabled",
        "TimeScale",
        "Color",
        "Opacity",
        "RiseVelocity",
        "Size",
    },
    ["SurfaceGui"] = {
        "ToolPunchThroughDistance",
        "Active",
        "Adornee",
        "Face",
        "ZOffset",
        "LightInfluence",
        "SizingMode",
        "PixelsPerStud",
        "ClipsDescendants",
        "Brightness",
        "AlwaysOnTop",
        "CanvasSize",
    },
    ["UIScale"] = {
        "Scale",
    },
    ["CFrameValue"] = {
        "Value",
    },
    ["InputObject"] = {
        "UserInputType",
        "KeyCode",
        "Position",
        "Delta",
        "UserInputState",
    },
    ["ImageLabel"] = {
        "ImageColor3",
        "ScaleType",
        "ImageTransparency",
        "IsLoaded",
        "Image",
        "TileSize",
        "ImageRectSize",
        "SliceScale",
        "ImageRectOffset",
        "ResampleMode",
        "SliceCenter",
    },
    ["NotificationService"] = {
        "SelectedTheme",
        "IsLuaGameDetailsEnabled",
    },
    ["UIListLayout"] = {
        "Padding",
    },
    ["Torque"] = {
        "Torque",
        "RelativeTo",
    },
    ["HandleAdornment"] = {
        "AdornCullingMode",
        "ZIndex",
        "CFrame",
        "AlwaysOnTop",
        "SizeRelativeOffset",
    },
    ["UniversalConstraint"] = {
        "LimitsEnabled",
        "Radius",
        "MaxAngle",
        "Restitution",
    },
    ["PointLight"] = {
        "Range",
    },
    ["TweenBase"] = {
        "PlaybackState",
    },
    ["DoubleConstrainedValue"] = {
        "Value",
        "MinValue",
        "MaxValue",
    },
    ["RocketPropulsion"] = {
        "CartoonFactor",
        "MaxTorque",
        "TargetRadius",
        "TurnD",
        "ThrustD",
        "MaxSpeed",
        "ThrustP",
        "Target",
        "MaxThrust",
        "Turnp",
        "TargetOffset",
    },
    ["CoreGui"] = {
        "Version",
        "SelectionImageObject",
    },
    ["CanvasGroup"] = {
        "GroupTransparency",
        "GroupColor",
    },
    ["PluginToolbarButton"] = {
        "Enabled",
        "ClickableWhenViewportHidden",
        "Icon",
    },
    ["SelectionPartLasso"] = {
        "Part",
    },
    ["DataModel"] = {
        "CreatorId",
        "PlaceId",
        "Genre",
        "PlaceVersion",
        "Workspace",
        "GameId",
        "JobId",
        "PrivateServerOwnerId",
        "PrivateServerId",
        "CreatorType",
    },
    ["Bone"] = {
        "Transform",
        "TransformedWorldCFrame",
        "TransformedCFrame",
    },
    ["TerrainRegion"] = {
        "SizeInCells",
    },
    ["Texture"] = {
        "OffsetStudsU",
        "StudsPerTileV",
        "OffsetStudsV",
        "StudsPerTileU",
    },
    ["PhysicsSettings"] = {
        "AreRegionsShown",
        "AreAwakePartsHighlighted",
        "AreAnchorsShown",
        "AreWorldCoordsShown",
        "IsTreeShown",
        "UseCSGv2",
        "ThrottleAdjustTime",
        "IsReceiveAgeShown",
        "AreJointCoordinatesShown",
        "AllowSleep",
        "ArePartCoordsShown",
        "AreOwnersShown",
        "AreAssembliesShown",
        "AreContactPointsShown",
        "AreModelCoordsShown",
        "ShowDecompositionGeometry",
        "DisableCSGv2",
        "IsInterpolationThrottleShown",
        "AreTimestepsShown",
        "PhysicsEnvironmentalThrottle",
        "AreUnalignedPartsShown",
        "AreBodyTypesShown",
        "AreContactIslandsShown",
        "AreMechanismsShown",
        "AreTerrainReplicationRegionsShown",
    },
    ["Script"] = {
        "Source",
    },
    ["Terrain"] = {
        "MaterialColors",
        "Decoration",
        "WaterReflectance",
        "WaterColor",
        "WaterTransparency",
        "WaterWaveSize",
        "WaterWaveSpeed",
        "MaxExtents",
    },
    ["DataStoreInfo"] = {
        "CreatedTime",
        "UpdatedTime",
        "DataStoreName",
    },
    ["LineHandleAdornment"] = {
        "Thickness",
        "Length",
    },
    ["RenderingTest"] = {
        "ComparisonDiffThreshold",
        "FieldOfView",
        "Description",
        "CFrame",
        "ComparisonMethod",
        "QualityLevel",
        "Position",
        "Orientation",
        "ComparisonPsnrThreshold",
        "ShouldSkip",
        "Ticket",
    },
    ["DepthOfFieldEffect"] = {
        "InFocusRadius",
        "FarIntensity",
        "FocusDistance",
        "NearIntensity",
    },
    ["HumanoidDescription"] = {
        "HatAccessory",
        "Face",
        "ProportionScale",
        "ClimbAnimation",
        "FrontAccessory",
        "AccessoryBlob",
        "RightArmColor",
        "HairAccessory",
        "RightArm",
        "Head",
        "FallAnimation",
        "TorsoColor",
        "DepthScale",
        "LeftArm",
        "HeightScale",
        "LeftLeg",
        "RightLegColor",
        "LeftLegColor",
        "JumpAnimation",
        "BodyTypeScale",
        "BackAccessory",
        "LeftArmColor",
        "GraphicTShirt",
        "WidthScale",
        "WalkAnimation",
        "WaistAccessory",
        "Torso",
        "SwimAnimation",
        "ShouldersAccessory",
        "Shirt",
        "HeadColor",
        "RunAnimation",
        "IdleAnimation",
        "RightLeg",
        "HeadScale",
        "Pants",
        "NeckAccessory",
        "FaceAccessory",
    },
    ["FunctionalTest"] = {
        "Description",
    },
    ["ServerScriptService"] = {
        "LoadStringEnabled",
    },
    ["BillboardGui"] = {
        "Active",
        "ExtentsOffset",
        "PlayerToHideFrom",
        "LightInfluence",
        "DistanceStep",
        "Brightness",
        "AlwaysOnTop",
        "Size",
        "ClipsDescendants",
        "Adornee",
        "ExtentsOffsetWorldSpace",
        "MaxDistance",
        "CurrentDistance",
        "SizeOffset",
        "StudsOffsetWorldSpace",
        "DistanceUpperLimit",
        "DistanceLowerLimit",
        "StudsOffset",
    },
    ["Feature"] = {
        "LeftRight",
        "InOut",
        "TopBottom",
        "FaceId",
    },
    ["BodyThrust"] = {
        "Location",
        "Force",
    },
    ["Team"] = {
        "AutoAssignable",
        "TeamColor",
    },
    ["FlangeSoundEffect"] = {
        "Depth",
        "Mix",
        "Rate",
    },
    ["EchoSoundEffect"] = {
        "Feedback",
        "DryLevel",
        "Delay",
        "WetLevel",
    },
    ["UIGridStyleLayout"] = {
        "VerticalAlignment",
        "FillDirection",
        "HorizontalAlignment",
        "AbsoluteContentSize",
        "SortOrder",
    },
    ["UITextSizeConstraint"] = {
        "MaxTextSize",
        "MinTextSize",
    },
    ["BodyGyro"] = {
        "P",
        "CFrame",
        "D",
        "MaxTorque",
    },
    ["WrapLayer"] = {
        "Enabled",
        "Color",
        "BindOffset",
        "ReferenceMeshId",
        "ReferenceOrigin",
        "ReferenceOriginWorld",
        "ShrinkFactor",
        "Order",
        "Puffiness",
        "DebugMode",
    },
    ["NoCollisionConstraint"] = {
        "Enabled",
        "Part1",
        "Part0",
    },
    ["SpecialMesh"] = {
        "MeshType",
    },
    ["RodConstraint"] = {
        "LimitAngle0",
        "Thickness",
        "LimitsEnabled",
        "Length",
        "CurrentDistance",
        "LimitAngle1",
    },
    ["FileMesh"] = {
        "TextureId",
        "MeshId",
    },
    ["Shirt"] = {
        "ShirtTemplate",
    },
    ["SlidingBallConstraint"] = {
        "LimitsEnabled",
        "MotorMaxAcceleration",
        "UpperLimit",
        "Velocity",
        "LinearResponsiveness",
        "LowerLimit",
        "CurrentPosition",
        "TargetPosition",
        "Size",
        "Restitution",
        "Speed",
        "ServoMaxForce",
        "MotorMaxForce",
        "ActuatorType",
    },
    ["FlagStand"] = {
        "TeamColor",
    },
    ["SkateboardPlatform"] = {
        "Throttle",
        "Controller",
        "StickyWheels",
        "ControllingHumanoid",
        "Steer",
    },
    ["DebuggerWatch"] = {
        "Expression",
    },
    ["DataModelMesh"] = {
        "Offset",
        "VertexColor",
        "Scale",
    },
    ["SkateboardController"] = {
        "Throttle",
        "Steer",
    },
    ["Beam"] = {
        "FaceCamera",
        "Color",
        "ZOffset",
        "LightInfluence",
        "Segments",
        "Attachment0",
        "Brightness",
        "TextureMode",
        "Attachment1",
        "Enabled",
        "TextureSpeed",
        "Width1",
        "CurveSize0",
        "Width0",
        "Transparency",
        "LightEmission",
        "TextureLength",
        "Texture",
        "CurveSize1",
    },
    ["BaseWrap"] = {
        "ImportOriginWorld",
        "CageOriginWorld",
        "ImportOrigin",
        "CageOrigin",
        "CageMeshId",
        "HSRAssetId",
    },
    ["Mouse"] = {
        "Origin",
        "y",
        "X",
        "ViewSizeX",
        "TargetFilter",
        "ViewSizeY",
        "Hit",
        "Target",
        "UnitRay",
        "Icon",
        "TargetSurface",
    },
    ["Constraint"] = {
        "Enabled",
        "Active",
        "Color",
        "Visible",
        "Attachment0",
        "Attachment1",
    },
    ["Decal"] = {
        "ZIndex",
        "Transparency",
        "Color3",
        "Texture",
    },
    ["ImageHandleAdornment"] = {
        "Size",
        "Image",
    },
    ["Clothing"] = {
        "Color3",
    },
    ["Lighting"] = {
        "ClockTime",
        "ColorShift_Bottom",
        "FogColor",
        "FogEnd",
        "EnvironmentDiffuseScale",
        "Brightness",
        "ColorShift_Top",
        "GlobalShadows",
        "EnvironmentSpecularScale",
        "TimeOfDay",
        "FogStart",
        "Ambient",
        "OutdoorAmbient",
        "Technology",
        "GeographicLatitude",
        "ShadowSoftness",
        "ExposureCompensation",
    },
    ["RenderSettings"] = {
        "MeshPartDetailLevel",
        "ExportMergeByMaterial",
        "AutoFRMLevel",
        "RenderCSGTrianglesDebug",
        "GraphicsMode",
        "EditQualityLevel",
        "QualityLevel",
        "ReloadAssets",
        "ShowBoundingBoxes",
        "EagerBulkExecution",
        "FrameRateManager",
        "MeshCacheSize",
    },
    ["ObjectValue"] = {
        "Value",
    },
    ["CharacterMesh"] = {
        "OverlayTextureId",
        "MeshId",
        "BaseTextureId",
        "BodyPart",
    },
    ["GameSettings"] = {
        "AdditionalCoreIncludeDirs",
        "OverrideStarterScript",
        "VideoCaptureEnabled",
        "VideoRecording",
    },
    ["FaceInstance"] = {
        "Face",
    },
    ["BodyColors"] = {
        "LeftArmColor3",
        "RightLegColor",
        "LeftLegColor",
        "HeadColor3",
        "HeadColor",
        "TorsoColor",
        "LeftArmColor",
        "TorsoColor3",
        "RightLegColor3",
        "RightArmColor",
        "RightArmColor3",
        "LeftLegColor3",
    },
    ["ColorCorrectionEffect"] = {
        "TintColor",
        "Brightness",
        "Saturation",
        "Contrast",
    },
    ["Speaker"] = {
        "Source",
        "SoundGroup",
        "PlaybackLoudness",
        "Volume",
        "RollOffMode",
        "RollOffMaxDistance",
        "ChannelCount",
        "RollOffMinDistance",
    },
    ["Atmosphere"] = {
        "Density",
        "Offset",
        "Color",
        "Decay",
        "Haze",
        "Glare",
    },
    ["RopeConstraint"] = {
        "WinchResponsiveness",
        "WinchTarget",
        "WinchEnabled",
        "Thickness",
        "WinchForce",
        "Restitution",
        "Length",
        "CurrentDistance",
        "WinchSpeed",
    },
    ["SelectionBox"] = {
        "SurfaceTransparency",
        "SurfaceColor3",
        "LineThickness",
    },
    ["FaceControls"] = {
        "ChinRaiser",
        "LeftUpperLipRaiser",
        "RightEyeClosed",
        "EyesLookDown",
        "EyesLookLeft",
        "LeftLowerLipDepressor",
        "TongueOut",
        "RightNoseWrinkler",
        "LeftCheekRaiser",
        "JawDrop",
        "LeftNoseWrinkler",
        "LipPresser",
        "FlatPucker",
        "LeftOuterBrowRaiser",
        "LeftEyeUpperLidRaiser",
        "JawLeft",
        "LeftDimpler",
        "UpperLipSuck",
        "LeftLipStretcher",
        "RightLipStretcher",
        "Corrugator",
        "LeftEyeClosed",
        "RightLipCornerDown",
        "TongueDown",
        "RightLipCornerPuller",
        "RightOuterBrowRaiser",
        "RightLowerLipDepressor",
        "RightUpperLipRaiser",
        "RightInnerBrowRaiser",
        "RightBrowLowerer",
        "LeftLipCornerDown",
        "TongueUp",
        "Funneler",
        "LeftInnerBrowRaiser",
        "RightCheekRaiser",
        "ChinRaiserUpperLip",
        "JawRight",
        "RightCheekPuff",
        "RightDimpler",
        "Pucker",
        "RightEyeUpperLidRaiser",
        "LowerLipSuck",
        "MouthLeft",
        "LipsTogether",
        "LeftLipCornerPuller",
        "EyesLookUp",
        "LeftCheekPuff",
        "LeftBrowLowerer",
        "MouthRight",
        "EyesLookRight",
    },
    ["DebugSettings"] = {
        "RobloxVersion",
        "DataModel",
        "PlayerCount",
        "ReportSoundWarnings",
        "TickCountPreciseOverride",
        "JobCount",
        "InstanceCount",
        "IsScriptStackTracingEnabled",
    },
    ["IntValue"] = {
        "Value",
    },
    ["FloorWire"] = {
        "CycleOffset",
        "WireRadius",
        "TextureSize",
        "From",
        "To",
        "Velocity",
        "StudsBetweenTextures",
        "Texture",
    },
    ["Motor"] = {
        "CurrentAngle",
        "DesiredAngle",
        "MaxVelocity",
    },
    ["Glue"] = {
        "F0",
        "F1",
        "F2",
        "F3",
    },
    ["ChatWindowConfiguration"] = {
        "Enabled",
    },
    ["UIGridLayout"] = {
        "FillDirectionMaxCells",
        "CellPadding",
        "AbsoluteCellCount",
        "StartCorner",
        "CellSize",
        "AbsoluteCellSize",
    },
    ["LayerCollector"] = {
        "Enabled",
        "ResetOnSpawn",
        "ZIndexBehavior",
    },
    ["TestService"] = {
        "Description",
        "Is30FpsThrottleEnabled",
        "AutoRuns",
        "IsPhysicsEnvironmentalThrottled",
        "ExecuteWithStudioRun",
        "TestCount",
        "Timeout",
        "NumberOfPlayers",
        "WarnCount",
        "SimulateSecondsLag",
        "IsSleepAllowed",
        "ErrorCount",
    },
    ["SoundGroup"] = {
        "Volume",
    },
    ["GuiObject"] = {
        "LayoutOrder",
        "Active",
        "Selectable",
        "AnchorPoint",
        "NextSelectionRight",
        "ZIndex",
        "AutomaticSize",
        "Size",
        "Visible",
        "ClipsDescendants",
        "BorderColor3",
        "SizeConstraint",
        "SelectionImageObject",
        "NextSelectionLeft",
        "Rotation",
        "NextSelectionUp",
        "BackgroundTransparency",
        "Position",
        "NextSelectionDown",
        "BorderSizePixel",
        "BorderMode",
        "BackgroundColor3",
    },
    ["DebuggerBreakpoint"] = {
        "Line",
        "ContinueExecution",
        "IsEnabled",
        "isContextDependentBreakpoint",
        "Condition",
        "LogExpression",
    },
    ["SunRaysEffect"] = {
        "Intensity",
        "Spread",
    },
    ["PoseBase"] = {
        "EasingStyle",
        "Weight",
        "EasingDirection",
    },
    ["Pose"] = {
        "CFrame",
    },
    ["AnimationTrack"] = {
        "WeightTarget",
        "Animation",
        "Looped",
        "TimePosition",
        "WeightCurrent",
        "IsPlaying",
        "Length",
        "Speed",
        "Priority",
    },
    ["PluginAction"] = {
        "StatusTip",
        "Text",
        "ActionId",
        "AllowBinding",
    },
    ["AlignPosition"] = {
        "RigidityEnabled",
        "Responsiveness",
        "Position",
        "ApplyAtCenterOfMass",
        "MaxVelocity",
        "Mode",
        "ReactionForceEnabled",
        "MaxForce",
    },
    ["InsertService"] = {
        "AllowClientInsertModels",
    },
    ["DraggerService"] = {
        "DraggerCoordinateSpace",
        "AnimateHover",
        "AlignDraggedObjects",
        "GeometrySnapColor",
        "ShowHover",
        "AngleSnapEnabled",
        "DraggerMovementMode",
        "LinearSnapEnabled",
        "ShowPivotIndicator",
        "LinearSnapIncrement",
        "PivotSnapToGeometry",
        "AngleSnapIncrement",
        "HoverAnimateFrequency",
        "CollisionsEnabled",
        "JointsEnabled",
        "HoverThickness",
    },
    ["Message"] = {
        "Text",
    },
    ["Player"] = {
        "DevCameraOcclusionMode",
        "AutoJumpEnabled",
        "CameraMaxZoomDistance",
        "UserId",
        "Character",
        "DevEnableMouseLock",
        "CanLoadCharacterAppearance",
        "TeamColor",
        "DevTouchCameraMode",
        "NameDisplayDistance",
        "Team",
        "RespawnLocation",
        "ReplicationFocus",
        "Neutral",
        "FollowUserId",
        "DevComputerCameraMode",
        "HealthDisplayDistance",
        "DisplayName",
        "GameplayPaused",
        "MembershipType",
        "DevTouchMovementMode",
        "AccountAge",
        "DevComputerMovementMode",
        "CharacterAppearanceId",
        "CameraMode",
        "CameraMinZoomDistance",
    },
    ["ContentProvider"] = {
        "RequestQueueSize",
        "BaseUrl",
    },
    ["PathfindingLink"] = {
        "Label",
        "Attachment1",
        "IsBidirectional",
        "Attachment0",
    },
    ["BoxHandleAdornment"] = {
        "Size",
    },
    ["ScrollingFrame"] = {
        "AutomaticCanvasSize",
        "AbsoluteWindowSize",
        "ScrollingDirection",
        "AbsoluteCanvasSize",
        "CanvasSize",
        "ScrollBarImageColor3",
        "MidImage",
        "ScrollBarImageTransparency",
        "CanvasPosition",
        "ElasticBehavior",
        "VerticalScrollBarPosition",
        "TopImage",
        "VerticalScrollBarInset",
        "ScrollingEnabled",
        "BottomImage",
        "ScrollBarThickness",
        "HorizontalScrollBarInset",
    },
    ["Humanoid"] = {
        "UseJumpPower",
        "AutoRotate",
        "AutoJumpEnabled",
        "WalkToPoint",
        "WalkToPart",
        "DisplayDistanceType",
        "HealthDisplayType",
        "SeatPart",
        "MoveDirection",
        "TargetPoint",
        "Sit",
        "BreakJointsOnDeath",
        "CameraOffset",
        "WalkSpeed",
        "NameDisplayDistance",
        "RootPart",
        "MaxSlopeAngle",
        "RigType",
        "Jump",
        "NameOcclusion",
        "RequiresNeck",
        "JumpPower",
        "DisplayName",
        "HipHeight",
        "AutomaticScalingEnabled",
        "Health",
        "PlatformStand",
        "FloorMaterial",
        "JumpHeight",
        "MaxHealth",
        "HealthDisplayDistance",
    },
    ["Highlight"] = {
        "Enabled",
        "OutlineTransparency",
        "DepthMode",
        "Adornee",
        "OutlineColor",
        "FillTransparency",
        "FillColor",
    },
    ["GuiService"] = {
        "CoreGuiNavigationEnabled",
        "TouchControlsEnabled",
        "GuiNavigationEnabled",
        "MenuIsOpen",
        "AutoSelectGuiEnabled",
        "SelectedObject",
    },
    ["AngularVelocity"] = {
        "ReactionTorqueEnabled",
        "RelativeTo",
        "AngularVelocity",
        "MaxTorque",
    },
    ["CylinderHandleAdornment"] = {
        "Height",
        "Angle",
        "Radius",
        "InnerRadius",
    },
    ["BloomEffect"] = {
        "Threshold",
        "Intensity",
        "Size",
    },
    ["Attachment"] = {
        "Visible",
        "WorldOrientation",
        "CFrame",
        "Axis",
        "WorldSecondaryAxis",
        "SecondaryAxis",
        "Position",
        "Orientation",
        "WorldPosition",
        "WorldCFrame",
        "WorldAxis",
    },
    ["Light"] = {
        "Color",
        "Brightness",
        "Shadows",
        "Enabled",
    },
    ["ImporterRootSettings"] = {
        "RigType",
        "MergeMeshes",
        "Anchored",
        "PolygonCount",
        "ImportAsModelAsset",
        "InsertInWorkspace",
        "FileDimensions",
        "WorldForward",
        "WorldUp",
        "ScaleUnit",
        "InvertNegativeFaces",
    },
    ["PitchShiftSoundEffect"] = {
        "Octave",
    },
    ["ImageButton"] = {
        "ImageColor3",
        "HoverImage",
        "ImageTransparency",
        "IsLoaded",
        "PressedImage",
        "ImageRectOffset",
        "Image",
        "TileSize",
        "ImageRectSize",
        "SliceScale",
        "ScaleType",
        "ResampleMode",
        "SliceCenter",
    },
    ["GuiBase2d"] = {
        "AbsoluteSize",
        "AutoLocalize",
        "AbsoluteRotation",
        "AbsolutePosition",
        "RootLocalizationTable",
    },
    ["DialogChoice"] = {
        "GoodbyeChoiceActive",
        "UserDialog",
        "ResponseDialog",
        "GoodbyeDialog",
    },
    ["NumberValue"] = {
        "Value",
    },
    ["JointInstance"] = {
        "Enabled",
        "Part1",
        "Active",
        "C1",
        "C0",
        "Part0",
    },
    ["CylindricalConstraint"] = {
        "AngularRestitution",
        "LowerAngle",
        "WorldRotationAxis",
        "MotorMaxAngularAcceleration",
        "ServoMaxTorque",
        "UpperAngle",
        "AngularLimitsEnabled",
        "TargetAngle",
        "AngularResponsiveness",
        "InclinationAngle",
        "AngularSpeed",
        "RotationAxisVisible",
        "CurrentAngle",
        "AngularActuatorType",
        "MotorMaxTorque",
        "AngularVelocity",
    },
    ["TerrainDetail"] = {
        "ColorMap",
        "NormalMap",
        "RoughnessMap",
        "MaterialPattern",
        "Face",
        "StudsPerTile",
        "MetalnessMap",
    },
    ["PluginMenu"] = {
        "Icon",
        "Title",
    },
    ["Accessory"] = {
        "AccessoryType",
    },
    ["LineForce"] = {
        "Magnitude",
        "ApplyAtCenterOfMass",
        "MaxForce",
        "ReactionForceEnabled",
        "InverseSquareLaw",
    },
    ["Skin"] = {
        "SkinColor",
    },
    ["KeyframeMarker"] = {
        "Value",
    },
    ["Animation"] = {
        "AnimationId",
    },
    ["IntConstrainedValue"] = {
        "Value",
        "MinValue",
        "MaxValue",
    },
    ["HttpService"] = {
        "HttpEnabled",
    },
    ["ChannelSelectorSoundEffect"] = {
        "Channel",
    },
    ["EqualizerSoundEffect"] = {
        "MidGain",
        "LowGain",
        "HighGain",
    },
    ["Model"] = {
        "LevelOfDetail",
        "WorldPivot",
        "PrimaryPart",
    },
    ["BodyAngularVelocity"] = {
        "P",
        "AngularVelocity",
        "MaxTorque",
    },
    ["VelocityMotor"] = {
        "CurrentAngle",
        "MaxVelocity",
        "DesiredAngle",
        "Hole",
    },
    ["PostEffect"] = {
        "Enabled",
    },
    ["Part"] = {
        "Shape",
    },
    ["ImporterMeshSettings"] = {
        "IgnoreVertexColors",
        "DoubleSided",
        "Anchored",
        "PolygonCount",
        "Dimensions",
    },
    ["DynamicRotate"] = {
        "BaseAngle",
    },
    ["TeleportOptions"] = {
        "ReservedServerAccessCode",
        "ServerInstanceId",
        "ShouldReserveServer",
    },
    ["ArcHandles"] = {
        "Axes",
    },
    ["Players"] = {
        "LocalPlayer",
        "BubbleChat",
        "PreferredPlayers",
        "RespawnTime",
        "MaxPlayers",
        "ClassicChat",
        "CharacterAutoLoads",
    },
    ["BaseScript"] = {
        "Disabled",
        "LinkedSource",
    },
    ["DataStoreObjectVersionInfo"] = {
        "CreatedTime",
        "IsDeleted",
        "Version",
    },
    ["RayValue"] = {
        "Value",
    },
    ["Camera"] = {
        "FieldOfViewMode",
        "FieldOfView",
        "HeadLocked",
        "CFrame",
        "NearPlaneZ",
        "ViewportSize",
        "CameraType",
        "Focus",
        "CameraSubject",
        "MaxAxisFieldOfView",
        "HeadScale",
        "DiagonalFieldOfView",
    },
    ["BodyForce"] = {
        "Force",
    },
    ["UIPageLayout"] = {
        "TouchInputEnabled",
        "TweenTime",
        "EasingStyle",
        "Animated",
        "Circular",
        "GamepadInputEnabled",
        "CurrentPage",
        "Padding",
        "ScrollWheelInputEnabled",
        "EasingDirection",
    },
    ["MarkerCurve"] = {
        "Length",
    },
    ["DistortionSoundEffect"] = {
        "Level",
    },
    ["UIPadding"] = {
        "PaddingBottom",
        "PaddingTop",
        "PaddingLeft",
        "PaddingRight",
    },
    ["BasePart"] = {
        "Anchored",
        "RightSurface",
        "Mass",
        "AssemblyAngularVelocity",
        "BottomSurface",
        "CanCollide",
        "RootPriority",
        "AssemblyMass",
        "AssemblyLinearVelocity",
        "Transparency",
        "Orientation",
        "AssemblyCenterOfMass",
        "MaterialVariant",
        "ResizeableFaces",
        "CanQuery",
        "Color",
        "Massless",
        "CollisionGroupId",
        "AssemblyRootPart",
        "Locked",
        "Material",
        "Size",
        "BackSurface",
        "TopSurface",
        "LeftSurface",
        "ResizeIncrement",
        "CenterOfMass",
        "CanTouch",
        "Reflectance",
        "Rotation",
        "CFrame",
        "BrickColor",
        "Position",
        "FrontSurface",
        "CustomPhysicalProperties",
        "CastShadow",
        "PivotOffset",
    },
    ["DataStoreKeyInfo"] = {
        "CreatedTime",
        "UpdatedTime",
        "Version",
    },
    ["PartAdornment"] = {
        "Adornee",
    },
    ["DataStoreService"] = {
        "AutomaticRetry",
    },
    ["TextButton"] = {
        "FontFace",
        "LineHeight",
        "TextStrokeColor3",
        "TextStrokeTransparency",
        "TextTruncate",
        "TextSize",
        "RichText",
        "TextFits",
        "TextColor3",
        "Text",
        "TextYAlignment",
        "ContentText",
        "Font",
        "TextWrapped",
        "TextXAlignment",
        "TextTransparency",
        "MaxVisibleGraphemes",
        "TextScaled",
        "TextBounds",
    },
    ["UIStroke"] = {
        "ApplyStrokeMode",
        "LineJoinMode",
        "Color",
        "Transparency",
        "Thickness",
        "Enabled",
    },
    ["Sound"] = {
        "IsPaused",
        "SoundGroup",
        "RollOffMode",
        "ChannelCount",
        "PlaybackSpeed",
        "RollOffMaxDistance",
        "Volume",
        "Playing",
        "IsLoaded",
        "TimeLength",
        "TimePosition",
        "PlaybackLoudness",
        "SoundId",
        "IsPlaying",
        "RollOffMinDistance",
        "Looped",
        "PlayOnRemove",
    },
    ["ViewportFrame"] = {
        "CurrentCamera",
        "Ambient",
        "ImageTransparency",
        "LightColor",
        "ImageColor3",
        "LightDirection",
    },
    ["SpawnLocation"] = {
        "Enabled",
        "TeamColor",
        "Neutral",
        "Duration",
        "AllowTeamChangeOnTouch",
    },
    ["BlurEffect"] = {
        "Size",
    },
    ["ScreenGui"] = {
        "IgnoreGuiInset",
        "DisplayOrder",
    },
    ["MaterialService"] = {
        "TerrainCobblestone",
        "WoodPlanksName",
        "TerrainMud",
        "TerrainAsphalt",
        "TerrainLimestone",
        "Brick",
        "BrickName",
        "SmoothPlasticName",
        "CorrodedMetalName",
        "Use2022Materials",
        "TerrainPavement",
        "GrassName",
        "IceName",
        "CrackedLavaName",
        "SandName",
        "LeafyGrassName",
        "WoodName",
        "CobblestoneName",
        "TerrainSandstone",
        "TerrainBrick",
        "TerrainIce",
        "ConcreteName",
        "BasaltName",
        "Marble",
        "CorrodedMetal",
        "DiamondPlateName",
        "FoilName",
        "FabricName",
        "AsphaltName",
        "SmoothPlastic",
        "RockName",
        "Concrete",
        "Fabric",
        "GraniteName",
        "SlateName",
        "SandstoneName",
        "LimestoneName",
        "Foil",
        "Cobblestone",
        "Slate",
        "Granite",
        "Plastic",
        "MudName",
        "TerrainBasalt",
        "PebbleName",
        "TerrainGround",
        "Grass",
        "Sand",
        "WoodPlanks",
        "Wood",
        "PavementName",
        "TerrainWoodPlanks",
        "MarbleName",
        "TerrainRock",
        "TerrainSnow",
        "SnowName",
        "TerrainLeafyGrass",
        "TerrainCrackedLava",
        "TerrainSlate",
        "TerrainSand",
        "TerrainSalt",
        "GlacierName",
        "GroundName",
        "TerrainGlacier",
        "TerrainConcrete",
        "SaltName",
        "PlasticName",
        "DiamondPlate",
        "Metal",
        "MetalName",
        "Pebble",
        "TerrainGrass",
        "Ice",
    },
    ["Dialog"] = {
        "GoodbyeChoiceActive",
        "InitialPrompt",
        "Tone",
        "GoodbyeDialog",
        "InUse",
        "ConversationDistance",
        "BehaviorType",
        "TriggerOffset",
        "Purpose",
        "TriggerDistance",
    },
    ["ForceField"] = {
        "Visible",
    },
    ["NumberPose"] = {
        "Value",
    },
    ["BodyVelocity"] = {
        "P",
        "Velocity",
        "MaxForce",
    },
    ["WrapTarget"] = {
        "Color",
        "Stiffness",
        "DebugMode",
    },
    ["StarterPlayer"] = {
        "CharacterWalkSpeed",
        "AutoJumpEnabled",
        "CameraMaxZoomDistance",
        "UserEmotesEnabled",
        "CharacterMaxSlopeAngle",
        "DevComputerCameraMovementMode",
        "HealthDisplayDistance",
        "NameDisplayDistance",
        "CharacterJumpHeight",
        "CharacterJumpPower",
        "LoadCharacterAppearance",
        "CharacterUseJumpPower",
        "EnableMouseLockOption",
        "DevTouchMovementMode",
        "CameraMode",
        "DevComputerMovementMode",
        "DevCameraOcclusionMode",
        "DevTouchCameraMovementMode",
        "CameraMinZoomDistance",
    },
    ["Color3Value"] = {
        "Value",
    },
    ["Clouds"] = {
        "Color",
        "Enabled",
        "Density",
        "Cover",
    },
    ["WeldConstraint"] = {
        "Enabled",
        "Part1",
        "Part0",
        "Active",
    },
    ["SoundService"] = {
        "AmbientReverb",
        "RolloffScale",
        "DopplerScale",
        "RespectFilteringEnabled",
        "DistanceFactor",
    },
    ["VoiceChatService"] = {
        "EnableDefaultVoice",
    },
    ["VideoFrame"] = {
        "Looped",
        "Video",
        "TimePosition",
        "Volume",
        "Resolution",
        "IsLoaded",
        "TimeLength",
        "Playing",
    },
    ["Seat"] = {
        "Disabled",
        "Occupant",
    },
    ["VehicleSeat"] = {
        "Disabled",
        "ThrottleFloat",
        "SteerFloat",
        "Occupant",
        "TurnSpeed",
        "Throttle",
        "AreHingesDetected",
        "Torque",
        "Steer",
        "MaxSpeed",
        "HeadsUpDisplay",
    },
    ["ImporterMaterialSettings"] = {
        "DiffuseFilePath",
        "NormalFilePath",
        "IsPbr",
        "RoughnessFilePath",
        "MetalnessFilePath",
    },
    ["Vector3Value"] = {
        "Value",
    },
    ["VRService"] = {
        "VREnabled",
        "GuiInputUserCFrame",
    },
    ["PlayerGui"] = {
        "CurrentScreenOrientation",
        "ScreenOrientation",
        "SelectionImageObject",
    },
    ["UserInputService"] = {
        "MouseEnabled",
        "VREnabled",
        "GyroscopeEnabled",
        "GamepadEnabled",
        "OnScreenKeyboardPosition",
        "MouseBehavior",
        "TouchEnabled",
        "OnScreenKeyboardVisible",
        "MouseIconEnabled",
        "MouseDeltaSensitivity",
        "KeyboardEnabled",
        "OnScreenKeyboardSize",
        "AccelerometerEnabled",
    },
    ["PathfindingModifier"] = {
        "PassThrough",
        "Label",
    },
    ["UserGameSettings"] = {
        "Fullscreen",
        "AllTutorialsDisabled",
        "CameraMode",
        "GraphicsQualityLevel",
        "ComputerMovementMode",
        "SavedQualityLevel",
        "StartScreenSize",
        "ControlMode",
        "HasEverUsedVR",
        "MasterVolume",
        "VignetteEnabled",
        "VRRotationIntensity",
        "TouchMovementMode",
        "ChatVisible",
        "VREnabled",
        "RotationType",
        "RCCProfilerRecordTimeFrame",
        "MouseSensitivity",
        "ComputerCameraMovementMode",
        "OnboardingsCompleted",
        "StartMaximized",
        "UsedCustomGuiIsVisibleToggle",
        "GamepadCameraSensitivity",
        "UsedCoreGuiIsVisibleToggle",
        "TouchCameraMovementMode",
        "StartScreenPosition",
        "UsedHideHudShortcut",
        "RCCProfilerRecordFrameRate",
    },
    ["Frame"] = {
        "Style",
    },
    ["UITableLayout"] = {
        "Padding",
        "FillEmptySpaceColumns",
        "FillEmptySpaceRows",
        "MajorAxis",
    },
    ["MaterialVariant"] = {
        "ColorMap",
        "NormalMap",
        "BaseMaterial",
        "MaterialPattern",
        "StudsPerTile",
        "RoughnessMap",
        "MetalnessMap",
    },
    ["UISizeConstraint"] = {
        "MinSize",
        "MaxSize",
    },
    ["RigidConstraint"] = {
        "Broken",
        "DestructionForce",
        "DestructionTorque",
        "DestructionEnabled",
    },
    ["GuiButton"] = {
        "Modal",
        "Selected",
        "Style",
        "AutoButtonColor",
    },
    ["ParticleEmitter"] = {
        "ZOffset",
        "ShapeStyle",
        "VelocityInheritance",
        "Transparency",
        "Color",
        "Drag",
        "FlipbookStartRandom",
        "TimeScale",
        "LightInfluence",
        "Texture",
        "Squash",
        "Lifetime",
        "Speed",
        "Brightness",
        "FlipbookLayout",
        "Size",
        "Enabled",
        "Acceleration",
        "RotSpeed",
        "SpreadAngle",
        "FlipbookIncompatible",
        "LockedToPart",
        "Rate",
        "ShapeInOut",
        "EmissionDirection",
        "ShapePartial",
        "Rotation",
        "Orientation",
        "LightEmission",
        "FlipbookMode",
        "Shape",
        "FlipbookFramerate",
    },
    ["Flag"] = {
        "TeamColor",
    },
    ["AlignOrientation"] = {
        "MaxTorque",
        "PrimaryAxis",
        "CFrame",
        "AlignType",
        "RigidityEnabled",
        "SecondaryAxis",
        "Responsiveness",
        "PrimaryAxisOnly",
        "Mode",
        "ReactionTorqueEnabled",
        "MaxAngularVelocity",
    },
    ["UICorner"] = {
        "CornerRadius",
    },
    ["UIAspectRatioConstraint"] = {
        "AspectRatio",
        "DominantAxis",
        "AspectType",
    },
    ["GuiBase3d"] = {
        "Visible",
        "Transparency",
        "Color3",
    },
    ["SphereHandleAdornment"] = {
        "Radius",
    },
    ["Plugin"] = {
        "GridSize",
        "CollisionEnabled",
    },
    ["TrussPart"] = {
        "Style",
    },
    ["TriangleMeshPart"] = {
        "CollisionFidelity",
    },
    ["TremoloSoundEffect"] = {
        "Duty",
        "Depth",
        "Frequency",
    },
    ["Translator"] = {
        "LocaleId",
    },
    ["TaskScheduler"] = {
        "ThreadPoolConfig",
        "SchedulerDutyCycle",
        "ThreadPoolSize",
        "SchedulerRate",
    },
    ["TorsionSpringConstraint"] = {
        "Damping",
        "Radius",
        "MaxTorque",
        "CurrentAngle",
        "Coils",
        "Restitution",
        "Stiffness",
        "MaxAngle",
        "LimitsEnabled",
    },
    ["Tool"] = {
        "Enabled",
        "RequiresHandle",
        "GripPos",
        "Grip",
        "GripForward",
        "CanBeDropped",
        "ToolTip",
        "ManualActivationOnly",
        "GripUp",
        "GripRight",
    },
    ["TextSource"] = {
        "UserId",
        "CanSend",
    },
    ["CustomEventReceiver"] = {
        "Source",
    },
    ["TextChatMessage"] = {
        "MessageId",
        "PrefixText",
        "Timestamp",
        "TextSource",
        "Status",
        "Text",
        "TextChannel",
        "Metadata",
    },
    ["TextLabel"] = {
        "FontFace",
        "LineHeight",
        "TextStrokeColor3",
        "TextStrokeTransparency",
        "TextTruncate",
        "TextSize",
        "RichText",
        "TextFits",
        "TextColor3",
        "Text",
        "TextYAlignment",
        "ContentText",
        "Font",
        "TextWrapped",
        "TextXAlignment",
        "TextTransparency",
        "MaxVisibleGraphemes",
        "TextScaled",
        "TextBounds",
    },
    ["SoundEffect"] = {
        "Enabled",
        "Priority",
    },
    ["TextChatService"] = {
        "CreateDefaultTextChannels",
        "CreateDefaultCommands",
        "ChatVersion",
    },
    ["TextChatMessageProperties"] = {
        "Text",
        "PrefixText",
    },
    ["Trail"] = {
        "Enabled",
        "FaceCamera",
        "TextureLength",
        "Texture",
        "Color",
        "Lifetime",
        "WidthScale",
        "MaxLength",
        "LightInfluence",
        "Transparency",
        "MinLength",
        "Attachment0",
        "LightEmission",
        "Brightness",
        "TextureMode",
        "Attachment1",
    },
    ["Sky"] = {
        "StarCount",
        "SkyboxUp",
        "MoonTextureId",
        "SkyboxBk",
        "CelestialBodiesShown",
        "SkyboxDn",
        "SkyboxLf",
        "SunTextureId",
        "SunAngularSize",
        "SkyboxFt",
        "SkyboxRt",
        "MoonAngularSize",
    },
    ["TextBox"] = {
        "MultiLine",
        "CursorPosition",
        "LineHeight",
        "TextStrokeColor3",
        "TextStrokeTransparency",
        "SelectionStart",
        "PlaceholderColor3",
        "TextYAlignment",
        "PlaceholderText",
        "TextSize",
        "ShowNativeInput",
        "TextEditable",
        "RichText",
        "TextFits",
        "TextColor3",
        "TextWrapped",
        "Text",
        "TextTruncate",
        "TextTransparency",
        "ContentText",
        "Font",
        "MaxVisibleGraphemes",
        "TextXAlignment",
        "TextBounds",
        "ClearTextOnFocus",
        "TextScaled",
        "FontFace",
    },
    ["DockWidgetPluginGui"] = {
        "HostWidgetWasRestored",
    },
    ["AnimationClip"] = {
        "Priority",
        "Loop",
    },
    ["DataStoreKey"] = {
        "KeyName",
    },
    ["TeleportAsyncResult"] = {
        "ReservedServerAccessCode",
        "PrivateServerId",
    },
    ["TextChatCommand"] = {
        "Enabled",
        "PrimaryAlias",
        "SecondaryAlias",
    },
    ["SurfaceSelection"] = {
        "TargetSurface",
    },
    ["HopperBin"] = {
        "BinType",
        "Active",
    },
    ["SurfaceAppearance"] = {
        "ColorMap",
        "NormalMap",
        "AlphaMode",
        "RoughnessMap",
        "MetalnessMap",
    },
    ["FloatCurve"] = {
        "Length",
    },
    ["ReflectionMetadataItem"] = {
        "Browsable",
        "ServerOnly",
        "EditingDisabled",
        "Deprecated",
        "ScriptContext",
        "IsBackend",
        "ClassCategory",
        "UIMaximum",
        "FFlag",
        "UIMinimum",
        "UINumTicks",
        "ClientOnly",
        "PropertyOrder",
        "Constraint",
        "EditorType",
    },
    ["Studio"] = {
        "ScriptTimeoutLength",
        "RuntimeUndoBehavior",
        "CommandBarLocalState",
        "DeprecatedObjectsShown",
        "Rulers",
        "OverrideCoreScripts",
        "Theme",
        "LuaDebuggerEnabled",
        "DisplayLanguage",
        "PluginsDir",
        "DefaultScriptFileDir",
        "Font",
        "ShowCorePackagesInExplorer",
        "PluginDebuggingEnabled",
        "PermissionLevelShown",
        "LocalAssetsFolder",
        "OverrideCoreScriptsDir",
    },
    ["Chat"] = {
        "BubbleChatEnabled",
        "LoadDefaultChat",
    },
    ["StringValue"] = {
        "Value",
    },
    ["Selection"] = {
        "SelectionThickness",
    },
    ["Workspace"] = {
        "StreamOutBehavior",
        "Gravity",
        "Retargeting",
        "FallenPartsDestroyHeight",
        "CurrentCamera",
        "TouchesUseCollisionGroups",
        "StreamingTargetRadius",
        "SignalBehavior",
        "PhysicsSteppingMethod",
        "StreamingPauseMode",
        "DistributedGameTime",
        "Terrain",
        "AllowThirdPartySales",
        "MeshPartHeadsAndAccessories",
        "InterpolationThrottling",
        "ClientAnimatorThrottling",
        "HumanoidOnlySetCollisionsOnStateChange",
        "StreamingMinRadius",
        "StreamingEnabled",
        "ReplicateInstanceDestroySetting",
        "AnimationWeightedBlendFix",
        "GlobalWind",
    },
    ["StarterGui"] = {
        "VirtualCursorMode",
        "ShowDevelopmentGui",
        "ScreenOrientation",
    },
    ["SelectionSphere"] = {
        "SurfaceColor3",
        "SurfaceTransparency",
    },
    ["GamepadService"] = {
        "GamepadCursorEnabled",
    },
    ["ProximityPrompt"] = {
        "Enabled",
        "GamepadKeyCode",
        "AutoLocalize",
        "ActionText",
        "Exclusivity",
        "MaxActivationDistance",
        "KeyboardKeyCode",
        "UIOffset",
        "Style",
        "ObjectText",
        "RequiresLineOfSight",
        "RootLocalizationTable",
        "HoldDuration",
        "ClickablePrompt",
    },
    ["SpotLight"] = {
        "Angle",
        "Range",
        "Face",
    },
    ["CompressorSoundEffect"] = {
        "Threshold",
        "GainMakeup",
        "Release",
        "Ratio",
        "SideChain",
        "Attack",
    },
    ["Sparkles"] = {
        "Enabled",
        "SparkleColor",
        "TimeScale",
    },
    ["VoiceSource"] = {
        "UserId",
    },
    ["SelectionPointLasso"] = {
        "Point",
    },
    ["ScriptDebugger"] = {
        "IsPaused",
        "CurrentLine",
        "IsDebugging",
        "Script",
    },
    ["RunService"] = {
        "ClientGitHash",
    },
    ["PluginGui"] = {
        "Title",
    },
    ["ReverbSoundEffect"] = {
        "Density",
        "WetLevel",
        "Diffusion",
        "DecayTime",
        "DryLevel",
    },
    ["StudioService"] = {
        "ShowConstraintDetails",
        "UseLocalSpace",
        "DraggerSolveConstraints",
        "StudioLocaleId",
        "ActiveScript",
        "RotateIncrement",
        "GridSize",
        "DrawConstraintsOnTop",
    },
    ["ReflectionMetadataClass"] = {
        "Insertable",
        "PreferredParent",
        "ExplorerOrder",
        "ExplorerImageIndex",
    },
    ["ProximityPromptService"] = {
        "Enabled",
        "MaxPromptsVisible",
    },
    ["InstanceAdornment"] = {
        "Adornee",
    },
    ["SpringConstraint"] = {
        "Damping",
        "Radius",
        "MaxForce",
        "MaxLength",
        "Thickness",
        "Coils",
        "Stiffness",
        "CurrentLength",
        "LimitsEnabled",
        "FreeLength",
        "MinLength",
    },
    ["Fire"] = {
        "Enabled",
        "Heat",
        "Color",
        "TimeScale",
        "SecondaryColor",
        "Size",
    },
    ["RotationCurve"] = {
        "Length",
    },
    ["PluginDragEvent"] = {
        "MimeType",
        "Sender",
        "Data",
        "Position",
    },
    ["Tween"] = {
        "Instance",
        "TweenInfo",
    },
    ["ChatInputBarConfiguration"] = {
        "Enabled",
        "TargetTextChannel",
    },
    ["Path"] = {
        "Status",
    },
    ["PartOperation"] = {
        "SmoothingAngle",
        "UsePartColor",
        "TriangleCount",
        "RenderFidelity",
    },
    ["Pants"] = {
        "PantsTemplate",
    },
    ["LuaSourceContainer"] = {
        "CurrentEditor",
    },
    ["PackageLink"] = {
        "PackageId",
        "Creator",
        "AutoUpdate",
        "Status",
        "PackageAssetName",
        "VersionNumber",
        "PermissionLevel",
    },
    ["ConeHandleAdornment"] = {
        "Height",
        "Radius",
    },
    ["PVAdornment"] = {
        "Adornee",
    },
    ["NetworkSettings"] = {
        "PrintStreamInstanceQuota",
        "ShowActiveAnimationAsset",
        "RenderStreamedRegions",
        "PrintPhysicsErrors",
        "HttpProxyURL",
        "HttpProxyEnabled",
        "IncomingReplicationLag",
        "PrintJoinSizeBreakdown",
        "RandomizeJoinInstanceOrder",
    },
    ["Motor6D"] = {
        "ParentName",
        "ChildName",
    },
    ["ModuleScript"] = {
        "Source",
        "LinkedSource",
    },
    ["BoolValue"] = {
        "Value",
    },
    ["MeshPart"] = {
        "MeshSize",
        "DoubleSided",
        "MeshId",
        "RenderFidelity",
        "TextureId",
    },
    ["Pages"] = {
        "IsFinished",
    },
    ["DataStoreOptions"] = {
        "AllScopes",
    },
    ["BodyPosition"] = {
        "Position",
        "D",
        "P",
        "MaxForce",
    },
    ["LocalizationService"] = {
        "SystemLocaleId",
        "RobloxLocaleId",
    },
    ["ClickDetector"] = {
        "MaxActivationDistance",
        "CursorIcon",
    },
    ["LinearVelocity"] = {
        "RelativeTo",
        "MaxForce",
        "VectorVelocity",
        "LineVelocity",
        "LineDirection",
        "VelocityConstraintMode",
        "SecondaryTangentAxis",
        "PlaneVelocity",
        "PrimaryTangentAxis",
    },
    ["Instance"] = {
        "Name",
        "ClassName",
        "Parent",
        "Archivable",
        "PropertyStatusStudio",
    },
    ["ImporterTextureSettings"] = {
        "FilePath",
    },
    ["BackpackItem"] = {
        "TextureId",
    },
    ["HingeConstraint"] = {
        "LimitsEnabled",
        "LowerAngle",
        "ServoMaxTorque",
        "UpperAngle",
        "AngularVelocity",
        "Radius",
        "AngularResponsiveness",
        "TargetAngle",
        "AngularSpeed",
        "Restitution",
        "CurrentAngle",
        "MotorMaxAcceleration",
        "MotorMaxTorque",
        "ActuatorType",
    },
    ["SurfaceLight"] = {
        "Angle",
        "Range",
        "Face",
    },
    ["ImporterBaseSettings"] = {
        "Id",
        "ShouldImport",
        "ImportName",
    },
    ["UIGradient"] = {
        "Enabled",
        "Transparency",
        "Color",
        "Rotation",
        "Offset",
    },
    ["Explosion"] = {
        "Visible",
        "BlastPressure",
        "BlastRadius",
        "DestroyJointRadiusPercent",
        "ExplosionType",
        "Position",
        "TimeScale",
    },
    ["EulerRotationCurve"] = {
        "RotationOrder",
    },
    ["CommandInstance"] = {
        "Enabled",
        "Checked",
        "AllowGUIAccessPoints",
        "Permission",
        "Name",
        "DefaultShortcut",
        "StatusTip",
        "Icon",
        "DisplayName",
    },
    ["ChorusSoundEffect"] = {
        "Depth",
        "Mix",
        "Rate",
    },
    ["Keyframe"] = {
        "Time",
    },
}

local Util = {}

Util.dictFind = function(dict, value)
    for _,v in next, dict do
        if _ == value then
            return v
        end
    end
    return false
end

Util.getInstanceProperties = function(_Instance)
    return Properties[_Instance.ClassName]
end

local Spoofed = {}
Util.spoofProperty = function(_Instance, _Property)
    if not Util.dictFind(Spoofed, _Instance) then
        Spoofed[_Instance] = {
            _Property,
            _Instance[_Property]
        }
    end
end

local hook
hook = hookmetamethod(game, "__index", newcclosure(function(_Instance, Key)
    local found = Util.dictFind(Spoofed, _Instance)
    if found and Key == found[2] then
        return hook(_Instance, found[3])
    end
    
    return hook(_Instance, Key)
end))

for _,v in next, Util.getInstanceProperties(game.Players.LocalPlayer.Character) do
    Util.spoofProperty(game.Players.LocalPlayer.Character, v)
end

--return Util
